import ProductCard from "@/components/ProductCard";
import { prisma } from "@/lib/prisma";
import Link from "next/link";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const params = await searchParams; const q=params.q?.trim(); const sort=params.sort ?? "newest"; const page=Math.max(1,Number(params.page??1)); const limit=24;
  const where={status:"PUBLISHED" as const,seller:{status:"APPROVED" as const},...(q?{OR:[{name:{contains:q,mode:"insensitive" as const}},{description:{contains:q,mode:"insensitive" as const}},{brand:{contains:q,mode:"insensitive" as const}},{sku:{contains:q,mode:"insensitive" as const}}]}:{})};
  const orderBy=sort==="price_asc"?{price:"asc" as const}:sort==="price_desc"?{price:"desc" as const}:sort==="rating"?{rating:"desc" as const}:{createdAt:"desc" as const};
  const [products,total]=await prisma.$transaction([prisma.product.findMany({where,orderBy,skip:(page-1)*limit,take:limit,select:{id:true,name:true,slug:true,price:true,compareAtPrice:true,rating:true,reviewCount:true,images:{where:{isPrimary:true},take:1},seller:{select:{businessName:true,slug:true}}}}),prisma.product.count({where})]);
  return <main className="mx-auto max-w-7xl px-4 py-10 lg:px-6"><div className="flex flex-col gap-5 rounded-3xl bg-slate-950 p-7 text-white md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-slate-400">MARKETPLACE</p><h1 className="mt-1 text-4xl font-black">Products</h1><p className="mt-2 text-slate-300">Search independent stores and compare products.</p></div><form className="flex w-full max-w-lg gap-2"><input name="q" defaultValue={q} placeholder="Search products, brands, SKU..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/10 px-4 py-3 outline-none placeholder:text-slate-500"/><button className="rounded-xl bg-white px-5 font-bold text-slate-950">Search</button></form></div><div className="mt-7 flex items-center justify-between"><p className="text-sm text-slate-500">{total} products</p><form><input type="hidden" name="q" value={q??""}/><select name="sort" defaultValue={sort} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" onChange={undefined}><option value="newest">Newest</option><option value="price_asc">Price low → high</option><option value="price_desc">Price high → low</option><option value="rating">Best rated</option></select></form></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>{total>limit?<div className="mt-10 flex justify-center gap-2">{page>1&&<Link className="rounded-xl border px-4 py-2" href={`/products?page=${page-1}${q?`&q=${encodeURIComponent(q)}`:""}`}>Previous</Link>}<span className="rounded-xl bg-slate-950 px-4 py-2 text-white">{page}</span>{page*limit<total&&<Link className="rounded-xl border px-4 py-2" href={`/products?page=${page+1}${q?`&q=${encodeURIComponent(q)}`:""}`}>Next</Link>}</div>:null}</main>
}
